### ISSUE TITLE
solusinya gimana nih?

### ISSUE THREAD

**Issue by hanyawibu** [Client-Developer-ID/discord-bot-tutorial#4]
![gimana](https://user-images.githubusercontent.com/69033855/89015275-f6c9a800-d340-11ea-8389-f51284d76e98.png)

**Comment by RanggaGultom** [comment]
join discord server
https://discord.gg/rfCascr
tanyakan disitu.

**Comment by KagChi** [comment]
member stonks

**Comment by Miouns** [comment]
toLowerCase jingan
